// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Profile documents */
interface ProfileDocumentData {
    /**
     * linkedIn field in *Profile*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: profile.linkedin
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    linkedin: prismicT.LinkField;
    /**
     * github field in *Profile*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: profile.github
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    github: prismicT.LinkField;
    /**
     * name field in *Profile*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: profile.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * avatarUrl field in *Profile*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: profile.avatarurl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    avatarurl: prismicT.LinkField;
    /**
     * whatsapp field in *Profile*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: profile.whatsapp
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    whatsapp: prismicT.KeyTextField;
    /**
     * location field in *Profile*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: profile.location
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    location: prismicT.KeyTextField;
}
/**
 * Profile document from Prismic
 *
 * - **API ID**: `profile`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfileDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ProfileDocumentData>, "profile", Lang>;
export type AllDocumentTypes = ProfileDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ProfileDocumentData, ProfileDocument, AllDocumentTypes };
    }
}
